apiVersion: v1
kind: Namespace
metadata:
  name: springboot-demo

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: springboot-demo
  name: demo
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: {IMAGE}
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  namespace: springboot-demo
  name: demo-service
  labels:
    app: demo
spec:
  selector:
    app: demo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: springboot-demo
  name: demo-ingress
  labels:
    app: demo
spec:
  rules:
    - host: demo.1.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: demo-service
                port:
                  number: 8080
